const traduzioni = [
  {
    categoria: "Oggetti",
    nome: "Fushigiri",
    nomeOriginale: "不死斬り",
    letturaOriginale: "Fushigiri",
    nomeVecchio: "Lama Mortale",
    icona: "img/sekiro_items/mortalblade.png",
    descrizioneOriginale: "死なぬ者さえ殺す大太刀<br>その赤き刃は、刀を抜いた者を一度殺す<br>回生の力なくば、不死斬りの主とはなれぬ<br><br>不死斬りならば、<br>蟲憑きにとどめ忍殺をすることができる<br><br>この刀は、長く仙峯寺に秘匿されていた<br>刻まれた銘は、「拝涙」<br>それがこの刀の真の名だ",
    traduzione: "Un'ōdachi in grado di uccidere persino gli immortali. La lama rossa uccide chiunque la sguaini, perciò, senza il potere della resurrezione, non si può diventare suoi proprietari.<br><br>Con la Fushigiri si può eseguire un assassinio shinobi sugli ospiti dell'insetto.<br><br>Questa katana è rimasta nascosta nel tempio Senpo per molto tempo. Sopra vi è inciso “拝涙” (lacrima venerata), il vero nome della katana.",
    note: "Significa letteralmente “ammazza-immortali”. Il kanji fushi (不死) è lo stesso utilizzato in Dark Souls per indicare gli immortali."
  },
  {
    categoria: "Oggetti",
    nome: "Loto d'acqua fragrante",
    nomeOriginale: "馨し水蓮",
    letturaOriginale: "Kaguwashi suiren",
    nomeVecchio: "Loto del palazzo",
    icona: "img/sekiro_items/lotus.png",
    descrizioneOriginale: "落ち谷の奥に咲いていた、青白い蓮の花<br>源の水が濃く溜まる場に咲くもの<br><br>雌の猿は、この花の香りを好む<br>ゆえに獅子猿は、大切に育てていた<br>己のつがいに供えるために<br><br>この花は源の香気を生む、香の材料の一つ<br>不死断ちのために、御子が求めるものだ",
    traduzione: "Fiore di loto pallido che sboccia nelle profondità della Valle delle Cadute. Fioriscono nei punti in cui le Acque della Sorgente si accumulano.<br><br>Le scimmie femmine amano la fragranza di questi fiori. Per questo motivo, la Scimmia Leonina lo stava facendo crescere con cura, per poterlo offrire alla propria compagna.<br><br>Questo fiore emana la fragranza della Sorgente ed è uno degli ingredienti dell'incenso. Il Miko lo cerca per recidere l'immortalità.",
    note: ""
  },
  {
    categoria: "Oggetti",
    nome: "Katashiro",
    nomeOriginale: "形代",
    letturaOriginale: "Katashiro",
    nomeVecchio: "Emblema spiritico",
    icona: "img/sekiro_items/emblem.png",
    descrizioneOriginale: "ただよう白い形代<br><br>人に限ったことではないが、<br>何か心残りがあれば、その想いが<br>幻として形を取って見えることがある<br><br>義手忍具など、形代を消費することで<br>使えるアクションがある",
    traduzione: "Katashiro bianco e fluttuante.<br><br>Se permane qualche forma di rimpianto, esso può assumere una forma fugace ma visibile. Non è un fenomeno esclusivo degli esseri umani.<br><br>Alcune azioni richiedono il consumo di Katashiro, come l’uso degli strumenti shinobi protesici.",
    note: "I katashiro sono bambole di carta utilizzate nei rituali shintoisti come sostituti simbolici degli esseri umani, su cui vengono trasferiti peccati e impurità (kegare)."
  },
  {
    categoria: "Oggetti",
    nome: "Kusabimaru",
    nomeOriginale: "楔丸",
    letturaOriginale: "Kusabimaru",
    nomeVecchio: "Kusabimaru",
    icona: "img/sekiro_items/kusabimaru.png",
    descrizioneOriginale: "主である竜胤の御子・九郎より授かった刀<br>葦名の庶家である、平田氏に伝わるもの<br><br>失っていたが、再び狼の手に戻った<br><br>楔丸の名には、願いが込められている<br>忍びは人を殺すが定めなれど、<br>一握の慈悲だけは、捨ててはならぬ…<br><br>その願い、時に刃が汲むこともあろうか",
    traduzione: "Katana donata dal padrone Kurō, il Miko del Lignaggio del Drago. È un oggetto che viene tramandato nel clan Hirata, ramo cadetto degli Ashina.<br><br>Era andata persa, ma ora è ritornata nelle mani del Lupo.<br><br>Nel nome Kusabimaru è racchiuso un desiderio: il destino di uno shinobi è quello di uccidere, ma non deve abbandonare quel briciolo di misericordia che gli rimane...<br><br>Potrà la lama, in certe occasioni, accogliere quel desiderio?",
    note: "Kusabi (楔) significa “vincolo” o “cuneo” e potrebbe rappresentare un’autocitazione di Hidetaka Miyazaki, già legata al simbolismo dei cunei in opere come il Tempio Cuneale (楔の神殿) in Demon’s Souls e le Cuneoliti (楔石) in Dark Souls. Maru (丸), invece, è un suffisso tradizionale giapponese usato in vari nomi propri o di oggetti."
  },
  {
    categoria: "Oggetti",
    nome: "Pietra parassitaria",
    nomeOriginale: "お宿り石",
    letturaOriginale: "Oyadori ishi",
    nomeVecchio: "Pietra del riparo",
    icona: "img/sekiro_items/shelterstone.png",
    descrizioneOriginale: "水生村の奥の祭壇に祀られていた石<br><br>源の水を長く飲んでいた者は、<br>体の内に石が宿ることがある<br><br>　お宿りは吉兆ぞ<br>　かぐわしく、輿入れ奉ろう<br>この石は源の香気を生む、香の材料の一つ<br>不死断ちのために、御子が求めるものだ",
    traduzione: "Una pietra deificata sull'altare che si trova dietro il villaggio Mibu.<br><br>Infesta il corpo di coloro che bevono le Acque della Sorgente da molto tempo.<br><br>“I parassiti sono di buon auspicio. Un dolce profumo va offerto per le processioni nuziali.”<br><br>Questa pietra emana la fragranza della Sorgente ed è uno degli ingredienti dell'incenso. Il Miko la cerca per recidere l'immortalità.",
    note: "Koshiire (輿入れ) significa letteralmente “entrare nel palanchino”, ma come termine composto indica più precisamente la processione nuziale tradizionale in cui la sposa veniva condotta alla casa dello sposo a bordo di un palanchino. In questo contesto, la “processione nuziale” può essere interpretata come un rito di passaggio analogo: una transizione dal mondo terreno al Palazzo, in cui si abbandona la vita precedente per accedere a una nuova condizione."
  },
  {
    categoria: "Oggetti",
    nome: "Protesi shinobi",
    nomeOriginale: "忍義手",
    letturaOriginale: "Ningishu",
    nomeVecchio: "Protesi shinobi",
    icona: "img/sekiro_items/shinobiprosthetic.png",
    descrizioneOriginale: "仏師から譲り受けた、忍びの義手<br><br>人のそれを模した偽骨を軸に、<br>絡繰りが施されている<br>この義手には、何かを仕込むことができそうだ<br><br>大小の傷が刻まれ<br>血や油がこびりついてはいるが、<br>手入れは行き届いている",
    traduzione: "Braccio artificiale shinobi, ricevuto dal Busshi.<br><br>Nonostante ci sia un osso finto che imita quello umano, al suo centro c'è un meccanismo karakuri nel quale possono essere montati strumenti.<br><br>È piena di graffi, grandi e piccoli, ed è sporca di sangue e olio. Ma è stata comunque mantenuta bene.",
    note: "Il karakuri è un’antica arte meccanica giapponese che raggiunse il suo massimo sviluppo durante il periodo Edo (1603-1868). Si basa su meccanismi nascosti, spesso molto complessi e ingegnosi. Un esempio emblematico sono le karakuri ningyō, tradizionali bambole meccaniche capaci di svolgere azioni sorprendenti, come servire il tè, scoccare frecce o persino scrivere kanji."
  },
  {
    categoria: "Tecniche",
    nome: "Tecnica del burattinaio",
    nomeOriginale: "傀儡の術",
    letturaOriginale: "Kairai no jutsu",
    nomeVecchio: "Ninjutsu del burattinaio",
    icona: "img/sekiro_items/ninjutsupuppeteer.png",
    descrizioneOriginale: "忍殺した者を傀儡として操る忍殺忍術<br>形代を消費して、使用する<br><br>この秘術は、本来散るべき命を、<br>一時、この世に押し留める<br><br>そうして傀儡とされた者は、<br>しばしの間、術者のために動こうとする<br>だが、やがて散る定めである",
    traduzione: "Ninjutsu che manipola chi ha subito un assassinio shinobi come fosse un burattino. Consuma Katashiro con l’uso.<br><br>Questa tecnica segreta trattiene fugacemente in questo mondo le vite che si sarebbero dovute spegnere.<br><br>Chi è stato trasformato in burattino verrà manovrato dall'utilizzatore per breve tempo, ma sarà presto destinato a morire.",
    note: ""
  },
  {
    categoria: "Tecniche",
    nome: "Tecnica del fumo di sangue",
    nomeOriginale: "血煙の術",
    letturaOriginale: "Chikemuri no jutsu",
    nomeVecchio: "Ninjutsu del fumo di sangue",
    icona: "img/sekiro_items/ninjutsubloodsmoke.png",
    descrizioneOriginale: "周囲に血の煙幕を生み出す忍殺忍術<br>形代を消費して、使用する<br><br>これは死をもって為す、忍びの秘術である<br>忍殺した者の血しぶきを血煙へと変え、<br>辺りの敵の眼から逃れることができる<br>その後、さらに殺すかは自在である<br><br>稀な死闘は、忍びを忍びたらしめる<br>ただ殺すのではなく、糧とせよ",
    traduzione: "Ninjutsu che genera una cortina di fumo col sangue. Consuma Katashiro con l’uso.<br><br>Questa è una tecnica segreta shinobi che sfrutta le uccisioni: trasforma lo spruzzo di sangue della vittima in fumo, permettendo di sfuggire agli occhi dei nemici vicini e di ucciderne altri.<br><br>I rari scontri all'ultimo sangue sono ciò che rendono uno shinobi tale. Non è semplice omicidio, ma nutrimento.",
    note: ""
  },
  {
    categoria: "Personaggi",
    nome: "Anayama il mercante",
    nomeOriginale: "物売りの穴山",
    letturaOriginale: "Monouri no Anayama",
    nomeVecchio: "Anayama il mercante",
    icona: "img/sekiro_chara/anayama.webp",
	descrizioneOriginale: "",
	traduzione: "Un bandito che il Lupo incontrò alla tenuta Hirata, quando una banda di ladri la razziò. In seguito ha abbandonato quella vita ed è diventato un mercante.",
    note: ""
  },
  {
    categoria: "Personaggi",
    nome: "Busshi",
    nomeOriginale: "仏師",
    letturaOriginale: "Busshi",
    nomeVecchio: "Scultore",
    icona: "img/sekiro_chara/sculptor.webp",
	descrizioneOriginale: "",
	traduzione: "Eremita che vive nel tempio in rovina, dove trascorre il tempo intagliando statue di Buddha nel legno. Salvò il Lupo dopo la sconfitta contro Gen'ichiro e gli donò la sua protesi shinobi.",
    note: ""
  },
  {
    categoria: "Personaggi",
    nome: "Ema la dottoressa",
    nomeOriginale: "薬師エマ",
    letturaOriginale: "Kusushi Ema",
    nomeVecchio: "Emma la cerusica",
    icona: "img/sekiro_chara/ema.webp",
	descrizioneOriginale: "",
	traduzione: "Quando era ancora bambina, il Busshi la salvò da un campo di battaglia e la affidò a un suo amico, Dogen, che la adottò. Per onorare il suo maestro, intraprese lo studio della medicina, diventando una dottoressa di grande talento.",
    note: ""
  },
  {
    categoria: "Personaggi",
    nome: "Hanbē l'immortale",
    nomeOriginale: "死なず半兵衛",
    letturaOriginale: "Shinazu Hanbē",
    nomeVecchio: "Hanbei, il Non-morto",
    icona: "img/sekiro_chara/hanbei.webp",
	descrizioneOriginale: "",
	traduzione: "Vive nei pressi del tempio in rovina e funge da compagno di allenamento per il Lupo, aiutandolo ad affinare le sue tecniche di assassinio, poiché è incapace di morire.",
    note: ""
  },
  {
    categoria: "Personaggi",
    nome: "Kurō il Miko",
    nomeOriginale: "御子　九郎",
    letturaOriginale: "Miko Kurō",
    nomeVecchio: "Kuro, l'Erede Divino",
    icona: "img/sekiro_chara/kuro.webp",
	descrizioneOriginale: "",
	traduzione: "Detentore del misterioso potere del Lignaggio del Drago e colui che il Lupo deve proteggere. Fu adottato e cresciuto dal clan Hirata, un ramo cadetto del clan Ashina.",
    note: ""
  },
  {
    categoria: "Personaggi",
    nome: "Lupo - Sekiro",
    nomeOriginale: "狼 - 隻狼",
    letturaOriginale: "Ōkami - Sekirō",
    nomeVecchio: "Lupo - Sekiro",
    icona: "img/sekiro_chara/sekiro.webp",
	descrizioneOriginale: "",
	traduzione: "Il Lupo, conosciuto anche come Sekiro, è il protagonista del gioco. In giovane età fu trovato su un campo di battaglia dal Gufo, che lo prese con sé e lo addestrò per farne uno shinobi. Il suo padre adottivo gli diede il compito di proteggere il Miko del Lignaggio del Drago.",
    note: ""
  },
  {
    categoria: "Personaggi",
    nome: "Miko della Giovinezza",
    nomeOriginale: "変若の御子",
    letturaOriginale: "Ochi no Miko",
    nomeVecchio: "Fanciulla celeste",
    icona: "img/sekiro_chara/rejuvenation.webp",
	descrizioneOriginale: "",
	traduzione: "È l'ultima Miko rimasta in vita a possedere il falso Lignaggio del Drago, creato dai monaci del tempio Senpō dopo aver abbandonato la loro fede nella ricercare dell'immortalità.",
    note: ""
  },
  {
    categoria: "Personaggi",
    nome: "Monaco del corridoio illusorio",
    nomeOriginale: "幻廊の僧",
    letturaOriginale: "Genrō no sō",
    nomeVecchio: "Monaco delle Sale dell'Illusione",
    icona: "img/sekiro_chara/illusory_hall_monk.webp",
	descrizioneOriginale: "",
	traduzione: "Monaco che medita nel corridoio illusorio. A differenza degli altri monaci del tempio Senpō, non si è lasciato corrompere dalla ricerca dell’immortalità.",
    note: ""
  },
  {
    categoria: "Luoghi",
    nome: "Castello di Ashina - Castello principale",
    nomeOriginale: "葦名城　本城",
    letturaOriginale: "Ashinajō honjō",
    nomeVecchio: "Castello Ashina",
    icona: "img/sekiro_area/ashina_castle.png",
	descrizioneOriginale: "鬼仏：<br><br>1. 葦名城　本城<br>2. 天守上階　武者侍り<br>3. 天守上階　葦名流伝場<br>4. 天守望楼<br>5. 天守上階　御子の間<br>6. 名残り墓<br>7. 白蛇の社<br>8. 捨て牢入口<br>9. 葦名城　水手曲輪<br>10. 抜け穴前",
	traduzione: "Onibotoke:<br><br>1. Castello di Ashina - Castello principale<br>2. Piano superiore del tenshu - Riposo dei guerrieri<br>3. Piano superiore del tenshu -  Denjo dello stile Ashina<br>4. Osservatorio del tenshu<br>5. Piano superiore del tenshu - Stanza del Miko<br>6. Resti di tombe<br>7. Santuario della Serpe Albina<br>8. Entrata della prigione abbandonata<br>9. Castello di Ashina - Kuruwa dei marinai<br>10. Davanti al passaggio sotterraneo",
    note: ""
  },
  {
    categoria: "Luoghi",
    nome: "Monte Kongō",
    nomeOriginale: "金剛山",
    letturaOriginale: "Kongōsan",
    nomeVecchio: "Monte Kongo",
    icona: "img/sekiro_area/mt_kongo.png",
	descrizioneOriginale: "鬼仏：<br><br>1. 金剛山　仙峯寺<br>2. 武者侍り<br>3. 境内<br>4. 本堂<br>5. 奥の院<br>6. 谷落ちの洞窟<br>7. 鐘鬼のお堂",
	traduzione: "Onibotoke:<br><br>1. Tempio Senpō - Monte Kongō<br>2. Shugendō<br>3. Terre del tempio<br>4. Edificio principale del tempio<br>5. Santuario interno<br>6. Grotta della Valle delle Cadute<br>7. Tempio dell'oni della campana",
    note: ""
  },
  {
    categoria: "Luoghi",
    nome: "Palazzo della Sorgente",
    nomeOriginale: "源の宮",
    letturaOriginale: "Minamoto no miya",
    nomeVecchio: "Palazzo della Sorgente",
    icona: "img/sekiro_area/palace.png",
	descrizioneOriginale: "鬼仏：<br><br>1. 源の宮<br>2. 朱の橋<br>3. 水生の御屋敷<br>4. 花見舞台<br>5. 大桜<br>6. 宮の内裏<br>7. 餌やり場<br>8. 壷の貴人<br>9. 神域",
	traduzione: "Onibotoke:<br><br>1. Palazzo della Sorgente<br>2. Ponte vermiglio<br>3. Villa di Mibu<br>4. Palco dell'hanami<br>5. Gran sakura<br>6. Dairi del Palazzo<br>7. Luogo in cui nutrire il koi<br>8. Nobile del vaso<br>9. Shin'iki",
    note: ""
  },
  {
    categoria: "Luoghi",
    nome: "Prigione abbandonata",
    nomeOriginale: "捨て牢",
    letturaOriginale: "Suterō",
    nomeVecchio: "Segrete",
    icona: "img/sekiro_area/dungeon.png",
	descrizioneOriginale: "鬼仏：<br><br>1. 地下水路<br>2. 武者侍り",
	traduzione: "Onibotoke:<br><br>1. Canale sotterraneo<br>2. Luogo in cui buttarsi nella morte",
    note: ""
  },
  {
    categoria: "Luoghi",
    nome: "Profondità di Ashina",
    nomeOriginale: "葦名の底",
    letturaOriginale: "Ashina no soko",
    nomeVecchio: "Abissi di Ashina",
    icona: "img/sekiro_area/depths.png",
	descrizioneOriginale: "鬼仏：<br><br>1. 葦名の底<br>2. 毒だまり<br>3. 獅子猿のねぐら<br>4. 隠し森<br>5. 水生村<br>6. 水車小屋<br>7. 輿入れの岩戸",
	traduzione: "Onibotoke:<br><br>1. Profondità di Ashina<br>2. Pantano velenoso<br>3. Tana della Scimmia Leonina<br>4. Foresta nascosta<br>5. Villaggio Mibu<br>6. Mulino ad acqua<br>7. Porta di pietra della processione nuziale",
    note: ""
  },
  {
    categoria: "Luoghi",
    nome: "Sponde della Fonte del Drago - Tenuta Hirata",
    nomeOriginale: "竜泉川端　平田屋敷",
    letturaOriginale: "Ryūsen kawabata Hirata yashiki",
    nomeVecchio: "Sponda della Fonte di Drago",
    icona: "img/sekiro_area/dragonspring.png",
	descrizioneOriginale: "鬼仏：<br><br>1. 竜泉川端　平田屋敷<br>2. 屋敷通り<br>3. 竹林坂<br>4. 平田屋敷　主殿<br>5. 平田屋敷　渡り廊下<br>6. 平田屋敷　隠し仏殿",
	traduzione: "Onibotoke:<br><br>1. Sponde della Fonte del Drago - Tenuta Hirata<br>2. Strada della tenuta<br>3. Pendio del bosco di bambù<br>4. Palazzo della tenuta Hirata<br>5. Passaggio tra gli edifici - Tenuta Hirata<br>6. Tempio dei buddha nascosto - Tenuta Hirata",
    note: ""
  },
  {
    categoria: "Luoghi",
    nome: "Terre vicine al Castello di Ashina",
    nomeOriginale: "葦名城　城下",
    letturaOriginale: "Ashinajō jōka",
    nomeVecchio: "Dintorni di Ashina",
    icona: "img/sekiro_area/ashina.png",
	descrizioneOriginale: "鬼仏：<br><br>1. 荒れ寺<br>2. 葦名城　城下<br>3. 城下外郭　城門路<br>4. 城下外郭　虎口階段<br>5. 橋下の谷<br>6. 大手門の出丸<br>7. 大手門<br>8. 怨嗟の炎",
	traduzione: "Onibotoke:<br><br>1. Tempio in rovina<br>2. Terre vicine al Castello di Ashina<br>3. Mura esterne delle terre vicine al castello - Strada per il cancello<br>4. Mura esterne delle terre vicine al castello - Scala per la tana della tigre<br>5. Valle sotto al ponte<br>6. Torre protettiva del cancello principale<br>7. Cancello principale<br>8. Fiamme del rancore",
    note: ""
  },
  {
    categoria: "Luoghi",
    nome: "Valle delle Cadute",
    nomeOriginale: "落ち谷",
    letturaOriginale: "Ochidani",
    nomeVecchio: "Forra",
    icona: "img/sekiro_area/sunken.png",
	descrizioneOriginale: "鬼仏：<br><br>1. 社下の谷<br>2. 落ち谷<br>3. 鉄砲砦<br>4. 落ち谷　奥廊下<br>5. 菩薩谷<br>6. 獅子猿の水場",
	traduzione: "Onibotoke:<br><br>1. Valle sotto al santuario<br>2. Valle delle Cadute<br>3. Forte dei Fucili<br>4. Passaggio nei recessi della Valle delle Cadute<br>5. Valle dei bosatsu<br>6. Stagno della Scimmia Leonina",
    note: ""
  }
];